name: yaga_storybook_app

description: A fairy-tale style multilingual book app

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  audioplayers: ^5.2.1
  provider: ^6.1.2
  url_launcher: ^6.3.1
  just_audio: ^0.9.36
  pdf: ^3.10.4
  path_provider: ^2.1.1
  flutter_dotenv: ^5.2.1
  lucide_icons: ^0.257.0
  flutter_svg: ^2.0.7
  open_filex: ^4.0.2
  turn_page_transition: ^0.4.0
  #page_flip: ^0.2.5+1


dependency_overrides:
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.4.8

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/sounds/
    - assets/icons/flags/
    - assets/icons/youtube.png
    - assets/icons/instagram.png
    - assets/icons/facebook.png
    - assets/coloring/
    - .env

  fonts:
    - family: FairyFont0
      fonts:
        - asset: assets/fonts/CormorantGaramond-Medium.ttf
    - family: FairyFont
      fonts:
        - asset: assets/fonts/CormorantGaramond-SemiBold.ttf
    - family: FairyFont1
      fonts:
        - asset: assets/fonts/Mak-ExtraBold.otf

    - family: FairyFont2
      fonts:
        - asset: assets/fonts/baloo-cyrillic.ttf
