name: yaga_storybook_app

description: A fairy-tale style multilingual book app

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  audioplayers: ^5.2.1
  provider: ^6.1.2
  url_launcher: ^6.3.1
  just_audio: ^0.9.36
  pdf: ^3.10.4
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.4.8

  

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/icons/youtube.png
    - assets/icons/instagram.png
    - assets/icons/facebook.png
    - assets/coloring/
    

fonts:
  - family: FairyFont
    fonts:
      - asset: assets/fonts/Forum-Regular.ttf

  - family: FairyFont1
    fonts:
      - asset: assets/fonts/Mak-ExtraBold.otf